import asyncio
import json
from types import SimpleNamespace

import pytest

from doug.backtest import harvest as harvest_mod
from doug.backtest.curve import capture_curve, rule_stats
from doug.backtest.harvest import HarvestedPR, _enrich_all, _load_partial
from doug.backtest.label import label_defects
from doug.backtest.replay import to_metadata


def _pr(number: int, title: str = "t", body: str = "", **kw) -> HarvestedPR:
    base = dict(
        number=number,
        title=title,
        body=body,
        author="dev",
        author_is_bot=False,
        additions=10,
        deletions=2,
        files=["src/a.py"],
        created_at="2026-01-01 10:00:00+00:00",
        merged_at="2026-01-02 10:00:00+00:00",
        approvals=1,
        first_approval_at="2026-01-01 11:30:00+00:00",
    )
    base.update(kw)
    return HarvestedPR.model_validate(base)


# --- labeling ---------------------------------------------------------------


def test_github_autogenerated_revert_body():
    prs = [_pr(100, title="Add caching"), _pr(101, title="Revert PR", body="Reverts acme/app#100")]
    assert label_defects(prs) == {100}


def test_revert_reference_in_title():
    prs = [_pr(7, title="Ship feature"), _pr(9, title="Revert #7, broke prod")]
    assert label_defects(prs) == {7}


def test_quoted_title_revert_without_number():
    prs = [_pr(40, title="Add rate limiter"), _pr(44, title='Revert "Add rate limiter"')]
    assert label_defects(prs) == {40}


def test_mention_without_revert_does_not_label():
    prs = [_pr(1, title="Add x"), _pr(2, title="Follow-up", body="Similar to #1")]
    assert label_defects(prs) == set()


def test_reference_outside_harvest_window_ignored():
    prs = [_pr(50, title="Revert old change", body="Reverts acme/app#3")]
    assert label_defects(prs) == set()


# --- replay mapping ---------------------------------------------------------


def test_approval_latency_computed_from_timestamps():
    meta = to_metadata(_pr(1))
    assert meta.approval_latency_s == 90 * 60


def test_unapproved_pr_has_no_latency():
    meta = to_metadata(_pr(1, approvals=0, first_approval_at=None))
    assert meta.approval_latency_s is None


def test_bot_author_mapped_to_agent():
    meta = to_metadata(_pr(1, author_is_bot=True))
    assert meta.author_type == "agent"


def test_module_recency_never_guessed():
    assert to_metadata(_pr(1)).days_since_last_human_commit is None


# --- harvest checkpoint/resume ----------------------------------------------
# A multi-hour harvest spans GitHub rate windows and can be killed mid-run;
# without incremental checkpoints every interruption re-spends the full quota.


def test_resume_skips_already_enriched(tmp_path, monkeypatch):
    partial = tmp_path / "run.partial.jsonl"
    partial.write_text(json.dumps(_pr(1).model_dump()) + "\n")
    enriched_numbers = []

    async def fake_enrich(gh, owner, repo, pull, sem):
        enriched_numbers.append(pull.number)
        return _pr(pull.number)

    monkeypatch.setattr(harvest_mod, "_enrich", fake_enrich)
    pulls = [SimpleNamespace(number=1), SimpleNamespace(number=2)]
    result = asyncio.run(_enrich_all(None, "o", "r", pulls, partial))

    assert enriched_numbers == [2]  # PR 1 came from the checkpoint, no API spend
    assert [p.number for p in result] == [1, 2]  # listing order preserved
    assert set(_load_partial(partial)) == {1, 2}


def test_progress_survives_mid_run_failure(tmp_path, monkeypatch):
    partial = tmp_path / "run.partial.jsonl"

    async def fake_enrich(gh, owner, repo, pull, sem):
        if pull.number == 2:
            raise RuntimeError("rate limit")
        return _pr(pull.number)

    monkeypatch.setattr(harvest_mod, "_enrich", fake_enrich)
    pulls = [SimpleNamespace(number=1), SimpleNamespace(number=2)]
    with pytest.raises(RuntimeError):
        asyncio.run(_enrich_all(None, "o", "r", pulls, partial))

    assert set(_load_partial(partial)) == {1}  # PR 1's work is not lost


def test_partial_removed_after_final_cache_written(tmp_path, monkeypatch):
    async def fake_harvest(owner, repo, limit, token, before, partial):
        return [_pr(1)]

    monkeypatch.setattr(harvest_mod, "_harvest", fake_harvest)
    stale = tmp_path / "o-r-1.partial.jsonl"
    stale.write_text(json.dumps(_pr(1).model_dump()) + "\n")

    result = harvest_mod.harvest("o", "r", 1, None, tmp_path)

    assert [p.number for p in result] == [1]
    assert (tmp_path / "o-r-1.json").exists()
    assert not stale.exists()  # checkpoint cleaned up once the real cache lands


# --- curve math -------------------------------------------------------------


def test_perfect_separation():
    scored = [(0.9, True), (0.8, True), (0.1, False), (0.1, False)]
    c = capture_curve(scored)
    assert c.capture_at(0.5) == 1.0
    # Max attainable AUC with 50% defect prevalence is 0.75.
    assert abs(c.auc - 0.75) < 1e-9


def test_ties_interpolate_linearly():
    # All PRs share one score: the curve must be the random diagonal,
    # not a favorable accidental ordering.
    scored = [(0.04, True), (0.04, False), (0.04, False), (0.04, False)]
    c = capture_curve(scored)
    assert abs(c.capture_at(0.5) - 0.5) < 1e-9
    assert abs(c.auc - 0.5) < 1e-9


def test_no_defects_yields_empty_curve():
    c = capture_curve([(0.5, False)])
    assert c.auc == 0.0


def test_rule_stats_lift():
    fired = [["a"], ["a"], [], []]
    defects = [True, False, False, False]
    stats = rule_stats(fired, defects)
    assert stats[0].rule == "a"
    assert stats[0].fired == 2
    assert stats[0].precision == 0.5
    assert stats[0].lift == 2.0  # base rate 25%, rule precision 50%
