import asyncio
import json
from types import SimpleNamespace

import pytest

from doug.backtest import harvest as harvest_mod
from doug.backtest.curve import capture_curve, cleared_band, rule_stats
from doug.backtest.harvest import (
    FileDetail,
    HarvestedPR,
    _enrich_all,
    _load_partial,
    backfill_file_details,
)
from doug.backtest.label import label_defects
from doug.backtest.replay import to_metadata


def _pr(number: int, title: str = "t", body: str = "", **kw) -> HarvestedPR:
    base = dict(
        number=number,
        title=title,
        body=body,
        author="dev",
        author_is_bot=False,
        additions=10,
        deletions=2,
        files=["src/a.py"],
        created_at="2026-01-01 10:00:00+00:00",
        merged_at="2026-01-02 10:00:00+00:00",
        approvals=1,
        first_approval_at="2026-01-01 11:30:00+00:00",
    )
    base.update(kw)
    return HarvestedPR.model_validate(base)


# --- labeling ---------------------------------------------------------------


def test_github_autogenerated_revert_body():
    prs = [_pr(100, title="Add caching"), _pr(101, title="Revert PR", body="Reverts acme/app#100")]
    assert label_defects(prs) == {100}


def test_revert_reference_in_title():
    prs = [_pr(7, title="Ship feature"), _pr(9, title="Revert #7, broke prod")]
    assert label_defects(prs) == {7}


def test_quoted_title_revert_without_number():
    prs = [_pr(40, title="Add rate limiter"), _pr(44, title='Revert "Add rate limiter"')]
    assert label_defects(prs) == {40}


def test_mention_without_revert_does_not_label():
    prs = [_pr(1, title="Add x"), _pr(2, title="Follow-up", body="Similar to #1")]
    assert label_defects(prs) == set()


def test_reference_outside_harvest_window_ignored():
    prs = [_pr(50, title="Revert old change", body="Reverts acme/app#3")]
    assert label_defects(prs) == set()


# --- replay mapping ---------------------------------------------------------


def test_approval_latency_computed_from_timestamps():
    meta = to_metadata(_pr(1))
    assert meta.approval_latency_s == 90 * 60


def test_unapproved_pr_has_no_latency():
    meta = to_metadata(_pr(1, approvals=0, first_approval_at=None))
    assert meta.approval_latency_s is None


def test_bot_author_mapped_to_agent():
    meta = to_metadata(_pr(1, author_is_bot=True))
    assert meta.author_type == "agent"


def test_module_recency_never_guessed():
    assert to_metadata(_pr(1)).days_since_last_human_commit is None


# --- harvest checkpoint/resume ----------------------------------------------
# A multi-hour harvest spans GitHub rate windows and can be killed mid-run;
# without incremental checkpoints every interruption re-spends the full quota.


def test_resume_skips_already_enriched(tmp_path, monkeypatch):
    partial = tmp_path / "run.partial.jsonl"
    partial.write_text(json.dumps(_pr(1).model_dump()) + "\n")
    enriched_numbers = []

    async def fake_enrich(gh, owner, repo, pull, sem):
        enriched_numbers.append(pull.number)
        return _pr(pull.number)

    monkeypatch.setattr(harvest_mod, "_enrich", fake_enrich)
    pulls = [SimpleNamespace(number=1), SimpleNamespace(number=2)]
    result = asyncio.run(_enrich_all(None, "o", "r", pulls, partial))

    assert enriched_numbers == [2]  # PR 1 came from the checkpoint, no API spend
    assert [p.number for p in result] == [1, 2]  # listing order preserved
    assert set(_load_partial(partial)) == {1, 2}


def test_progress_survives_mid_run_failure(tmp_path, monkeypatch):
    partial = tmp_path / "run.partial.jsonl"

    async def fake_enrich(gh, owner, repo, pull, sem):
        if pull.number == 2:
            raise RuntimeError("rate limit")
        return _pr(pull.number)

    monkeypatch.setattr(harvest_mod, "_enrich", fake_enrich)
    pulls = [SimpleNamespace(number=1), SimpleNamespace(number=2)]
    with pytest.raises(RuntimeError):
        asyncio.run(_enrich_all(None, "o", "r", pulls, partial))

    assert set(_load_partial(partial)) == {1}  # PR 1's work is not lost


def test_partial_removed_after_final_cache_written(tmp_path, monkeypatch):
    async def fake_harvest(owner, repo, limit, token, before, partial):
        return [_pr(1)]

    monkeypatch.setattr(harvest_mod, "_harvest", fake_harvest)
    stale = tmp_path / "o-r-1.partial.jsonl"
    stale.write_text(json.dumps(_pr(1).model_dump()) + "\n")

    result = harvest_mod.harvest("o", "r", 1, None, tmp_path)

    assert [p.number for p in result] == [1]
    assert (tmp_path / "o-r-1.json").exists()
    assert not stale.exists()  # checkpoint cleaned up once the real cache lands


# --- file-details backfill --------------------------------------------------
# v4 light-diff features need per-file stats + patch text. Old caches predate
# the field; backfill fetches only what's missing, checkpointed like harvest.


def _detail(name: str = "src/a.py") -> FileDetail:
    return FileDetail(
        filename=name, status="modified", additions=3, deletions=1, patch="@@ -1 +1 @@"
    )


def test_old_cache_loads_with_details_absent(tmp_path):
    (tmp_path / "o-r-1.json").write_text(json.dumps([_pr(1).model_dump(exclude={"file_details"})]))
    result = harvest_mod.harvest("o", "r", 1, None, tmp_path)
    assert result[0].file_details is None  # None = never fetched, [] = fetched-and-empty


def test_backfill_fetches_only_missing(tmp_path, monkeypatch):
    cache = tmp_path / "o-r-2.json"
    done = _pr(1, file_details=[_detail()])
    todo = _pr(2)
    cache.write_text(json.dumps([done.model_dump(), todo.model_dump()]))
    fetched = []

    async def fake_fetch(gh, owner, repo, number, sem):
        fetched.append(number)
        return [_detail("src/b.py")]

    monkeypatch.setattr(harvest_mod, "_fetch_file_details", fake_fetch)
    n = backfill_file_details("o", "r", 2, None, tmp_path)

    assert fetched == [2] and n == 1  # PR 1 already had details, no API spend
    reloaded = harvest_mod.harvest("o", "r", 2, None, tmp_path)
    assert [p.file_details is not None for p in reloaded] == [True, True]
    assert reloaded[1].file_details[0].filename == "src/b.py"
    assert not (tmp_path / "o-r-2.details.jsonl").exists()


def test_backfill_checkpoint_survives_failure(tmp_path, monkeypatch):
    cache = tmp_path / "o-r-2.json"
    original = json.dumps([_pr(1).model_dump(), _pr(2).model_dump()])
    cache.write_text(original)

    async def flaky_fetch(gh, owner, repo, number, sem):
        if number == 2:
            raise RuntimeError("rate limit")
        return [_detail()]

    monkeypatch.setattr(harvest_mod, "_fetch_file_details", flaky_fetch)
    with pytest.raises(RuntimeError):
        backfill_file_details("o", "r", 2, None, tmp_path)

    assert cache.read_text() == original  # money cache untouched on failure
    sidecar = tmp_path / "o-r-2.details.jsonl"
    assert sidecar.exists()  # PR 1's fetch survived

    calls = []

    async def fake_fetch(gh, owner, repo, number, sem):
        calls.append(number)
        return [_detail()]

    monkeypatch.setattr(harvest_mod, "_fetch_file_details", fake_fetch)
    n = backfill_file_details("o", "r", 2, None, tmp_path)
    assert calls == [2]  # PR 1 came from the sidecar — no API re-spend
    assert n == 2  # but both PRs' details landed in the cache this call
    assert all(p.file_details for p in harvest_mod.harvest("o", "r", 2, None, tmp_path))


# --- curve math -------------------------------------------------------------


def test_perfect_separation():
    scored = [(0.9, True), (0.8, True), (0.1, False), (0.1, False)]
    c = capture_curve(scored)
    assert c.capture_at(0.5) == 1.0
    # Max attainable AUC with 50% defect prevalence is 0.75.
    assert abs(c.auc - 0.75) < 1e-9


def test_ties_interpolate_linearly():
    # All PRs share one score: the curve must be the random diagonal,
    # not a favorable accidental ordering.
    scored = [(0.04, True), (0.04, False), (0.04, False), (0.04, False)]
    c = capture_curve(scored)
    assert abs(c.capture_at(0.5) - 0.5) < 1e-9
    assert abs(c.auc - 0.5) < 1e-9


def test_no_defects_yields_empty_curve():
    c = capture_curve([(0.5, False)])
    assert c.auc == 0.0


def test_rule_stats_lift():
    fired = [["a"], ["a"], [], []]
    defects = [True, False, False, False]
    stats = rule_stats(fired, defects)
    assert stats[0].rule == "a"
    assert stats[0].fired == 2
    assert stats[0].precision == 0.5
    assert stats[0].lift == 2.0  # base rate 25%, rule precision 50%


def test_harvest_dedupes_listing(tmp_path, monkeypatch):
    # Offset pagination can repeat a PR when a rate-limit retry re-fetches
    # a page boundary; one PR must never become two rows in the sample.
    async def fake_harvest(owner, repo, limit, token, before, partial):
        return [_pr(1), _pr(2), _pr(1)]

    monkeypatch.setattr(harvest_mod, "_harvest", fake_harvest)
    result = harvest_mod.harvest("o", "r", 3, None, tmp_path)
    assert [p.number for p in result] == [1, 2]


def test_cleared_band_is_empty_of_defects_when_ranking_is_perfect():
    # 2 defects, both ranked top. Flag 20% of 10 PRs and the cleared band is
    # clean — the only case where auto-merging what Doug cleared is free.
    scored = [(0.9, True), (0.8, True)] + [(0.1 * i / 100, False) for i in range(8)]
    band = cleared_band(capture_curve(scored), n=10, total_defects=2, flag_rate=0.20)
    assert band.cleared_prs == 8
    assert band.cleared_defects == pytest.approx(0.0)
    assert band.miss_rate == pytest.approx(0.0)
    assert band.density == pytest.approx(0.0)
    assert band.density_lift == pytest.approx(0.0)


def test_cleared_band_matches_base_rate_when_ranking_is_uninformative():
    # All scores tied => flagging is random => the cleared band is exactly as
    # risky as the population. density_lift ~1 means clearing told you nothing.
    scored = [(0.5, i < 10) for i in range(100)]
    band = cleared_band(capture_curve(scored), n=100, total_defects=10, flag_rate=0.20)
    assert band.density_lift == pytest.approx(1.0, abs=0.01)
    assert band.miss_rate == pytest.approx(0.8, abs=0.01)


def test_cleared_band_miss_rate_is_the_complement_of_capture():
    scored = [(float(100 - i), i % 7 == 0) for i in range(100)]
    curve = capture_curve(scored)
    total = sum(1 for _, d in scored if d)
    for r in (0.10, 0.20, 0.30):
        band = cleared_band(curve, n=100, total_defects=total, flag_rate=r)
        assert band.miss_rate == pytest.approx(1 - curve.capture_at(r))


def test_cleared_band_reports_zero_lift_for_an_empty_population():
    band = cleared_band(capture_curve([]), n=0, total_defects=0, flag_rate=0.20)
    assert band.density == 0.0
    assert band.density_lift == 0.0


def test_concurrent_checkpoints_land_whole(tmp_path):
    """Checkpoint appends now run in worker threads so a big harvest's
    10,000+ writes stop pausing every in-flight request. Off-loop writes
    can interleave without the lock, and a torn line silently loses the
    resume state the checkpoint exists to protect — every line must
    survive concurrency intact.
    """
    path = tmp_path / "partial.jsonl"

    async def hammer():
        lock = asyncio.Lock()
        payloads = [{"number": i, "pad": "x" * 2000} for i in range(50)]
        await asyncio.gather(
            *(
                harvest_mod._checkpoint(lock, path, json.dumps(p) + "\n")
                for p in payloads
            )
        )

    asyncio.run(hammer())
    lines = [json.loads(s) for s in path.read_text().splitlines() if s.strip()]
    assert sorted(p["number"] for p in lines) == list(range(50))
